[env.development]
name = "impretam3d-dev"
workers_dev = true

[env.production]
name = "impretam3d"
workers_dev = true

# Updated configuration for newer Wrangler
pages_build_output_dir = "./"
compatibility_date = "2025-05-29"
